name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (main branch)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure we're on the main branch to generate the build folder

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Adjust as necessary for your environment

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the `main.py` script to generate static content
      - name: Run main.py to generate static website
        run: |
          python main.py  # This should generate your static files, e.g., in the 'build' folder

      # Step 5: Create gh-pages branch if it doesn't exist
      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages

      # Step 6: Remove existing content from gh-pages
      - name: Clean up existing content on gh-pages
        run: |
          git rm -rf .  # Remove any existing files in the gh-pages branch

      # Step 7: Copy content from main branch to gh-pages
      - name: Copy content from main to gh-pages
        run: |
          git checkout main -- .  # Copy all files from main branch to gh-pages

      # Step 8: Rename 'build' folder to 'docs'
      - name: Rename build folder to docs
        run: |
          mv build docs  # Rename 'build' folder to 'docs'

      # Step 9: Commit and push changes to gh-pages
      - name: Commit and push changes to gh-pages
        run: |
          git add .
          git commit -m "Deploy static files to GitHub Pages"
          git push origin gh-pages --force
