name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the `main.py` script to generate static content
      - name: Run main.py to generate static website
        run: |
          python main.py  # This should generate your static files in the 'build' folder

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          git rm -rf .
          cp -r build/* .
          git add .
          git commit -m "Deploy static files to GitHub Pages"
          git push origin gh-pages