name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the `main` branch (or any branch you want)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # You can adjust the Python version as needed

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build project (if necessary)
      # If your project requires a build step (e.g., generating static files), include it here
      # For example, if you're using a static site generator like Jekyll, Hugo, or Pelican:
      - name: Build static site
        run: |
          # Example for Pelican, adjust to your needs
          pelican content -o output -s pelicanconf.py
          
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.0
        with:
          branch: gh-pages  # The branch you want to deploy to
          folder: output  # The folder containing your generated site (adjust if necessary)

      # Optional Step 6: Clean up (delete the build folder if desired)
      # - name: Clean up build
      #   run: rm -rf output  # Adjust if you're using a different folder name
